### ISSUE TITLE
[FeatureRequest] disable flags multiple click

### ISSUE THREAD

**Issue by tpr-evilempire** [seratch/deepl-for-slack#23]
Hello,
First of all, thanks a lot for sharing that very nice tool ! Much appreciated.

We are using it for few hours now, but we already facing an issue people not respecting the easy "no multiple flags" rules on messages.

Is there any way to prevent people to do that or, better said, not having the API call if someone already clicked that once ?

Thanks

**Comment by seratch** [comment]
Hi, my apologies for the delayed response. Unfortunately, there is no mechanism in place to prevent users from adding reactions using the Slack interface. Nonetheless, this app won't post translation results when an identical one has already been posted in the thread. Therefore, I don't believe there's a critical problem with this scenario. Let me close this now.
