### ISSUE TITLE
DeepL Translating documents (beta) Support

### ISSUE THREAD

**Issue by lsmith77** [seratch/deepl-for-slack#3]
have you given any thought to making it possible to get files translated via slack?

**Comment by seratch** [comment]
@lsmith77 No, I haven't and I don't have any plans to work on it. If you are going to implement such, utilizing another service (I don't have any recommendation though) for scanning the text content of a given file and upload its DeepL translation results as a new file in thread may be a possible solution.

**Comment by lsmith77** [comment]
ah didn’t mean OCR, “just” integration of their beta API for document uploads https://www.deepl.com/docs-api/translating-documents/

would you be open to a PR adding such functionality?

**Comment by seratch** [comment]
Oh, thanks for sharing this! I didn't know they added this cool feature.

Not only for your suggestion, I myself don't have the bandwidth to add new functionalities to this app in the short term (I will continue maintaining this though). That being said, once documents translation API is GAed, I may be interested in adding the feature. For this reason, please continue with your fork or your own project first. I will keep this issue open.

**Comment by lsmith77** [comment]
ok great!

**Comment by seratch** [comment]
After this discussion, I've created a new sample app for this: https://github.com/seratch/deepl-document-translator-for-slack
