### ISSUE TITLE
Node version?

### ISSUE THREAD

**Issue by oceam** [seratch/deepl-for-slack#5]
hi 
I was following your Qiita page and successfully deploied 2 weeks before. 
but when I try today, got error message from Heroku. can you teach me how to check it?
the full log is below:

-----> Building on the Heroku-20 stack
-----> Deleting 1 files matching .slugignore patterns.
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 14.x...
       Downloading and installing node 14.17.6...
       Using default npm version: 6.14.15
       
-----> Installing dependencies
       Installing node modules
       
       > nodemon@2.0.12 postinstall /tmp/build_ddbc3522/node_modules/nodemon
       > node bin/postinstall || exit 0
       
       Love nodemon? You can now support the project via the open collective:
        > https://opencollective.com/nodemon/donate
       
       added 277 packages in 6.195s
       
-----> Build
       Running build
       
       > deepl-for-slack@1.0.0 build /tmp/build_ddbc3522
       > tsc -p .
       
       src/runnner.ts(71,11): error TS2322: Type 'Option[]' is not assignable to type 'PlainTextOption[]'.
         Type 'Option' is not assignable to type 'PlainTextOption'.
           Type 'MrkdwnOption' is not assignable to type 'PlainTextOption'.
             The types of 'text.type' are incompatible between these types.
               Type '"mrkdwn"' is not assignable to type '"plain_text"'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! deepl-for-slack@1.0.0 build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the deepl-for-slack@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.Qmp7p/_logs/2021-09-12T14_28_44_164Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by seratch** [comment]
@oceam Thanks for reporting this! I've fixed this issue in the latest revision 👋

**Comment by oceam** [comment]
thank you very much!
