### ISSUE TITLE
Translations posting multiple times

### ISSUE THREAD

**Issue by Cheru-x** [seratch/deepl-for-slack#7]
It appears that when people are using the flag button and only clicking it once, it will post the translation multiple times. 

My current suspicion is that if someone makes a post, and then immediatly edits it. The translation (when it happens) occurs multiple times for each version - although I cannot prove this. 

I'm not a coder, but I was wondering if you could help me solve this?

**Comment by seratch** [comment]
If the translated text is not exactly the same, this app can post a message in thread again. I'm not planning to change this behavior.

**Comment by Cheru-x** [comment]
Thank you for sharing. 

I have also found an instance where the translation is posting multiple times, but there was no edit on the post. 
![image](https://user-images.githubusercontent.com/95453621/144529762-bb53ce3a-72fd-4aa4-b0ea-f1d9e34af70c.png)

**Comment by seratch** [comment]
Thanks for sharing the details! Hmm, indeed, posting the English text several times is an unexpected behavior. I'm still unsure why this is happening in your environment yet...

**Comment by Cheru-x** [comment]
How can I help you work this out?

**Comment by seratch** [comment]
If you provide the steps to reproduce the issue, that'd be appreciated.

**Comment by seratch** [comment]
I don't have anything further to help you out here. Let me close this issue now. If you find a bug in this app, please feel free to reopen this issue with detailed information.
